import type { SchemaObject } from "@nestjs/swagger/dist/interfaces/open-api-spec.interface";

const string: SchemaObject = { type: "string" };
const nullableString: SchemaObject = { type: "string", nullable: true };
const number: SchemaObject = { type: "number" };
const nullableNumber: SchemaObject = { type: "number", nullable: true };
const boolean: SchemaObject = { type: "boolean" };
const packageSchema: SchemaObject = {
  type: "object",
  required: ["version", "checksumSha256", "zoomMin", "zoomMax", "publishedAt"],
  properties: {
    version: { type: "integer", minimum: 1 },
    checksumSha256: nullableString,
    zoomMin: { type: "integer", minimum: 0, maximum: 22 },
    zoomMax: { type: "integer", minimum: 0, maximum: 22 },
    publishedAt: { type: "string", format: "date-time", nullable: true },
  },
};

export const offlineManifestResponseSchema: SchemaObject = {
  type: "object",
  required: ["data"],
  properties: {
    data: {
      type: "object",
      required: [
        "city",
        "package",
        "boundary",
        "bounds",
        "centers",
        "establishments",
        "pois",
        "routes",
      ],
      properties: {
        city: {
          type: "object",
          required: [
            "slug",
            "name",
            "canton",
            "province",
            "latitude",
            "longitude",
            "package",
          ],
          properties: {
            slug: string,
            name: string,
            canton: string,
            province: string,
            latitude: nullableNumber,
            longitude: nullableNumber,
            package: { ...packageSchema, nullable: true },
          },
        },
        package: packageSchema,
        boundary: {
          type: "object",
          additionalProperties: true,
          nullable: true,
        },
        bounds: {
          type: "array",
          minItems: 4,
          maxItems: 4,
          items: number,
          description: "Cobertura en orden oeste, sur, este, norte.",
        },
        centers: {
          type: "array",
          items: {
            type: "object",
            required: [
              "code",
              "name",
              "description",
              "latitude",
              "longitude",
              "category",
              "type",
              "subtype",
              "hierarchy",
              "categoryCode",
              "typeCode",
              "subtypeCode",
              "provinceCode",
              "cantonCode",
              "parishCode",
              "hierarchyCode",
            ],
            properties: {
              code: string,
              name: string,
              description: nullableString,
              latitude: number,
              longitude: number,
              category: string,
              type: string,
              subtype: string,
              hierarchy: nullableString,
              categoryCode: string,
              typeCode: string,
              subtypeCode: string,
              provinceCode: string,
              cantonCode: string,
              parishCode: string,
              hierarchyCode: nullableString,
            },
          },
        },
        establishments: {
          type: "array",
          items: {
            type: "object",
            required: [
              "id",
              "name",
              "activity",
              "classification",
              "category",
              "categoryLabel",
              "address",
              "phone",
              "localityName",
              "latitude",
              "longitude",
              "approximate",
              "icon",
              "group",
            ],
            properties: {
              id: { type: "integer", minimum: 1 },
              name: string,
              activity: string,
              classification: nullableString,
              category: nullableString,
              categoryLabel: nullableString,
              address: nullableString,
              phone: nullableString,
              localityName: string,
              latitude: number,
              longitude: number,
              approximate: boolean,
              icon: string,
              group: nullableString,
            },
          },
        },
        pois: {
          type: "array",
          items: {
            type: "object",
            required: [
              "key",
              "name",
              "description",
              "category",
              "latitude",
              "longitude",
              "icon",
            ],
            properties: {
              key: string,
              name: string,
              description: nullableString,
              category: nullableString,
              latitude: number,
              longitude: number,
              icon: string,
            },
          },
        },
        routes: {
          type: "array",
          items: {
            type: "object",
            required: [
              "key",
              "publicKey",
              "name",
              "origin",
              "destination",
              "durationMinutes",
              "durationEstimated",
              "transportCode",
              "distanceMeters",
              "geometry",
              "directions",
            ],
            properties: {
              key: string,
              publicKey: string,
              name: string,
              origin: string,
              destination: string,
              durationMinutes: nullableNumber,
              durationEstimated: boolean,
              transportCode: nullableString,
              distanceMeters: nullableNumber,
              geometry: {
                type: "object",
                required: ["type", "coordinates"],
                properties: {
                  type: { type: "string", enum: ["LineString"] },
                  coordinates: {
                    type: "array",
                    items: {
                      type: "array",
                      minItems: 2,
                      maxItems: 2,
                      items: number,
                    },
                  },
                },
              },
              directions: { type: "array", items: {} },
            },
          },
        },
      },
    },
  },
};
