import type { LucideIcon, LucideProps } from "lucide-react-native";
import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bike,
  Bookmark,
  Bot,
  BriefcaseBusiness,
  BusFront,
  CalendarDays,
  CarFront,
  Check,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  CircleHelp,
  Compass,
  Coffee,
  CornerUpLeft,
  CornerUpRight,
  Download,
  Eye,
  EyeOff,
  Flag,
  Footprints,
  History,
  Hotel,
  Landmark,
  LocateFixed,
  Mars,
  Map,
  MapPin,
  MapPinned,
  Menu,
  MessageCircle,
  Moon,
  Navigation,
  Pencil,
  Plus,
  RefreshCw,
  Redo2,
  Route,
  Search,
  Send,
  Settings,
  Share2,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Sun,
  SunMoon,
  Ticket,
  Undo2,
  Utensils,
  Wine,
  UserRound,
  Users,
  Venus,
  WifiOff,
  X,
} from "lucide-react-native";

import { turismoIconSizes } from "./tokens";

const turismoIconMap = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  bike: Bike,
  bookmark: Bookmark,
  bot: Bot,
  briefcase: BriefcaseBusiness,
  bus: BusFront,
  calendar: CalendarDays,
  car: CarFront,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circleHelp: CircleHelp,
  help: CircleHelp,
  compass: Compass,
  coffee: Coffee,
  cornerUpLeft: CornerUpLeft,
  cornerUpRight: CornerUpRight,
  download: Download,
  eye: Eye,
  eyeOff: EyeOff,
  flag: Flag,
  foot: Footprints,
  history: History,
  locate: LocateFixed,
  genderMale: Mars,
  genderFemale: Venus,
  hotel: Hotel,
  landmark: Landmark,
  map: Map,
  mapPin: MapPin,
  mapPinned: MapPinned,
  menu: Menu,
  message: MessageCircle,
  moon: Moon,
  navigation: Navigation,
  pencil: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  redo: Redo2,
  route: Route,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  sunMoon: SunMoon,
  ticket: Ticket,
  undo: Undo2,
  restaurant: Utensils,
  wine: Wine,
  user: UserRound,
  users: Users,
  wifiOff: WifiOff,
  close: X,
} as const satisfies Record<string, LucideIcon>;

export type TurismoIconName = keyof typeof turismoIconMap;

export function TurismoIcon({
  name,
  size = turismoIconSizes.md,
  color = "currentColor",
  strokeWidth = 2,
  ...props
}: Readonly<{ name: TurismoIconName } & Omit<LucideProps, "ref">>) {
  const Icon = turismoIconMap[name];
  return (
    <Icon
      aria-hidden
      color={color}
      size={size}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
